id: ACBBF883C
title: 'The Drumbeat of Immortality: A Prayer for the Long Life of the Great Tertön
  Dudjom Jigdral Yeshe Dorje'
type: translation
pechas:
- I8A0D0985
- I3104A2D1
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2023-01-04 11:48:24.640820
  last_modified_at: 2023-01-04 11:48:24.640833
  collections:
  - Dudjom Rinpoche Series
  - Works of Tibetan Masters
alignment_to_base:
  I8A0D0985/EE6B: CEB7
  I3104A2D1/34DB: CEB7
